using System;
using System.Collections.Generic;

#nullable disable

namespace WebApplication3.Model
{
    public partial class ReportTemplateHeader
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Col1Name { get; set; }
        public string Col2Name { get; set; }
        public string Col3Name { get; set; }
        public string Col4Name { get; set; }
        public DateTime? Col1YearEnd { get; set; }
        public int? Col1PeriodFrom { get; set; }
        public int? Col1PeriodTo { get; set; }
        public DateTime? Col2YearEnd { get; set; }
        public int? Col2PeriodFrom { get; set; }
        public int? Col2PeriodTo { get; set; }
        public DateTime? Col3YearEnd { get; set; }
        public int? Col3PeriodFrom { get; set; }
        public int? Col3PeriodTo { get; set; }
        public DateTime? Col4YearEnd { get; set; }
        public int? Col4PeriodFrom { get; set; }
        public int? Col4PeriodTo { get; set; }
        public bool? Col1Used { get; set; }
        public bool? Col2Used { get; set; }
        public bool? Col3Used { get; set; }
        public bool? Col4Used { get; set; }
        public bool? Col3Variance { get; set; }
        public bool? Col1Budget { get; set; }
        public bool? Col2Budget { get; set; }
        public bool? Col3Budget { get; set; }
        public bool? Col4Budget { get; set; }
        public bool? UseMerge { get; set; }
        public string Col1Costing { get; set; }
        public string Col2Costing { get; set; }
        public string Col3Costing { get; set; }
        public string Col4Costing { get; set; }
        public string Col5Name { get; set; }
        public string Col6Name { get; set; }
        public DateTime? Col5YearEnd { get; set; }
        public int? Col5PeriodFrom { get; set; }
        public int? Col5PeriodTo { get; set; }
        public DateTime? Col6YearEnd { get; set; }
        public int? Col6PeriodFrom { get; set; }
        public int? Col6PeriodTo { get; set; }
        public bool? Col5Used { get; set; }
        public bool? Col6Used { get; set; }
        public bool? Col4Variance { get; set; }
        public bool? Col5Variance { get; set; }
        public bool? Col6Variance { get; set; }
        public bool? Col5Budget { get; set; }
        public bool? Col6Budget { get; set; }
        public string Col5Costing { get; set; }
        public string Col6Costing { get; set; }
        public string Col7Name { get; set; }
        public bool? Col7Used { get; set; }
        public DateTime? Col7YearEnd { get; set; }
        public int? Col7PeriodFrom { get; set; }
        public int? Col7PeriodTo { get; set; }
        public bool? Col7Variance { get; set; }
        public bool? Col7Budget { get; set; }
        public string Col7Costing { get; set; }
        public string Col8Name { get; set; }
        public bool? Col8Used { get; set; }
        public DateTime? Col8YearEnd { get; set; }
        public int? Col8PeriodFrom { get; set; }
        public int? Col8PeriodTo { get; set; }
        public bool? Col8Variance { get; set; }
        public bool? Col8Budget { get; set; }
        public string Col8Costing { get; set; }
        public string Col9Name { get; set; }
        public bool? Col9Used { get; set; }
        public DateTime? Col9YearEnd { get; set; }
        public int? Col9PeriodFrom { get; set; }
        public int? Col9PeriodTo { get; set; }
        public bool? Col9Variance { get; set; }
        public bool? Col9Budget { get; set; }
        public string Col9Costing { get; set; }
        public string Col10Name { get; set; }
        public bool? Col10Used { get; set; }
        public DateTime? Col10YearEnd { get; set; }
        public int? Col10PeriodFrom { get; set; }
        public int? Col10PeriodTo { get; set; }
        public bool? Col10Variance { get; set; }
        public bool? Col10Budget { get; set; }
        public string Col10Costing { get; set; }
        public string Col11Name { get; set; }
        public bool? Col11Used { get; set; }
        public DateTime? Col11YearEnd { get; set; }
        public int? Col11PeriodFrom { get; set; }
        public int? Col11PeriodTo { get; set; }
        public bool? Col11Variance { get; set; }
        public bool? Col11Budget { get; set; }
        public string Col11Costing { get; set; }
        public string Col12Name { get; set; }
        public bool? Col12Used { get; set; }
        public DateTime? Col12YearEnd { get; set; }
        public int? Col12PeriodFrom { get; set; }
        public int? Col12PeriodTo { get; set; }
        public bool? Col12Variance { get; set; }
        public bool? Col12Budget { get; set; }
        public string Col12Costing { get; set; }
        public bool? ShowTotal { get; set; }
        public bool? Col1Curr { get; set; }
        public bool? Col2Curr { get; set; }
        public bool? Col3Curr { get; set; }
        public bool? Col4Curr { get; set; }
        public bool? Col5Curr { get; set; }
        public bool? Col6Curr { get; set; }
        public bool? Col7Curr { get; set; }
        public bool? Col8Curr { get; set; }
        public bool? Col9Curr { get; set; }
        public bool? Col10Curr { get; set; }
        public bool? Col11Curr { get; set; }
        public bool? Col12Curr { get; set; }
        public bool? IncludeOb { get; set; }
    }
}
